taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from manager import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.get_manager_list, name='get_manager_list'),
    path('add/', views.add_item, name='add'),

    path('edit/<item_id>', views.edit_item, name='edit'),
    path('toggle/<item_id>', views.toggle_item, name='toggle'),
    path('delete/<item_id>', views.delete_item, name='delete'),
    path('accounts/', include('allauth.urls')),

    path('projects/', views.ProjectView.as_view(), name='projects'),
    path('add_project/', views.AddProject.as_view(), name='add_project'),
    path('update_project/<pk>', views.ProjectUpdateView.as_view(),
         name='update_project'),
    path('delete_project/<pk>', views.ProjectDeleteView.as_view(),
         name='delete_project'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Project(models.Model):
    """ Projects list """
    name = models.CharField(max_length=300)

    def __str__(self):
        """[class objects as a string]"""
        return self.name

    def get_absolute_url(self):
        """[define absolute url for views classes]"""
        return reverse('get_manager_list')


class Item(models.Model):
    """ Project task list items """
    project = models.CharField(max_length=300, default='Not assigned')
    task = models.CharField(max_length=300, null=False, blank=False)
    owner = models.CharField(max_length=50, null=False, blank=False)
    due_date = models.DateField(null=False)
    done = models.BooleanField(null=False, blank=False, default=False)

    def __str__(self):
        """[class objects as a string]"""
        return self.task

manager/forms.py
from django import forms
from .models import Item, Project


class ProjectChoices(forms.ModelForm):
    """[Project Choices ]"""
    project_choices = Project.objects.all().values_list('name', 'name')
    project_list = []
    for choice in project_choices:
        project_list.append(choice)


class DateInput(forms.DateInput):
    """[to define input type for calendar picker]"""
    input_type = 'date'


class ItemForm(forms.ModelForm):
    """ form items """
    class Meta:
        """[ fields list and widget ]"""
        model = Item

        fields = ['project', 'task', 'owner', 'due_date', 'done']
        widgets = {
            'due_date': DateInput(attrs={'class': 'form-control'}),
            'task': forms.TextInput(attrs={'class': 'form-control'}),
            'owner': forms.TextInput(attrs={'class': 'form-control'}),
            'project': forms.Select(choices=ProjectChoices.project_list,
                                    attrs={'class': 'form-control'}),
        }

manager/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from .models import Item, Project
from .forms import ItemForm
from .filters import DueDateFilter

# Create your views here. """ using classes"""


class HomeView(ListView):
    """[add home view template]"""
    model = Item
    template_name = 'manager/manager_list.html'
    ordering = ['due_date']


class ProjectView(ListView):
    """[project view template]"""
    model = Project
    template_name = 'manager/projects.html'


class AddProject(CreateView):
    """ add project function """
    model = Project
    template_name = 'manager/add_project.html'
    fields = '__all__'


class ProjectUpdateView(UpdateView):
    """ add project function """
    model = Project
    template_name = 'manager/update_project.html'
    fields = '__all__'


class ProjectDeleteView(DeleteView):
    """ add project function """
    model = Project
    template_name = 'manager/delete_project.html'
    success_url = reverse_lazy('get_manager_list')


# Create your views here. """ using classes"""


def get_manager_list(request):
    """ manager list view"""
    context = {}
    my_filter = DueDateFilter(request.GET,
                              queryset=Item.objects.all().order_by('due_date'), )
    context['my_filter'] = my_filter
    paginated_filtered = Paginator(my_filter.qs, 7)
    page = request.GET.get('page')
    page_items = paginated_filtered.get_page(page)
    context['page_items'] = page_items
    return render(request, 'manager/manager_list.html', context=context)


def add_item(request):
    """ add item function """
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('get_manager_list')
    form = ItemForm()
    context = {
        'form': form
    }
    return render(request, 'manager/add_item.html', context)


def edit_item(request, item_id):
    """ edit item function """
    item = get_object_or_404(Item, id=item_id)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('get_manager_list')
    form = ItemForm(instance=item)
    context = {
        'form': form
    }
    return render(request, 'manager/edit_item.html', context)


def toggle_item(request, item_id):
    """ toggle items """
    item = get_object_or_404(Item, id=item_id)
    item.done = not item.done
    item.save()
    return redirect('get_manager_list')


def delete_item(request, item_id):
    """ delete items """
    item = get_object_or_404(Item, id=item_id)

    item.delete()
    return redirect('get_manager_list')

manager/templates/manager/add_item.html
{% extends 'base.html' %}


{% block content %}
<!-- Add task field -->
<div class="row action_field">
    <div class="col">
        <h2>Add task to the list:</h2>
        <form class="add_task" method="POST" enctype="multipart/form-data" action="{% url 'add' %}">

            {% csrf_token %}
            <!-- form Add task -->
            <div>
                {{ form.as_p }}
            </div>
            <br>
            <div>
                <p>
                    <button class="btn btn-primary" type="submit">Add Item</button>
                </p>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

manager/templates/manager/add_project.html
{% extends 'base.html' %}


{% block content %}
<!-- Add Project Area -->
<div class="row action_field">
    <div class="col center">

        <h2>Add project to the project list:</h2>
        <form method="POST" enctype="multipart/form-data" action="{% url 'add_project' %}">

            {% csrf_token %}
            <!-- form for adding project -->
            {{ form.as_p }}
            <br>
            <div>
                <p>
                    <button class="btn btn-primary" type="submit">Add Project</button>
                </p>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

manager/templates/manager/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List task</title>
    
</head>

<body>
    <div id="site">
        <div class="navigation">
            <nav class="navbar navbar-dark bg-dark navbar-default navbar-static-top">
                <div class="container-fluid">
                    <a class="navbar-brand nav-font" href="{% url 'get_manager_list' %}">Task Manager</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                        data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
                        aria-labelledby="offcanvasNavbarLabel">
                        <div class="offcanvas-header">
                            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Task Manager</h5>
                            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                                aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body bg-dark">
                            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page"
                                        href="{% url 'get_manager_list' %}">Home</a>
                                </li>
                                {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'add_project' %}">Add Project</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown"
                                        role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Coming Soon
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                                        <li><a class="dropdown-item" href="#">Gantt Chart</a></li>
                                        <li><a class="dropdown-item" href="#">Critical Path</a></li>
                                        <li><a class="dropdown-item" href="#">RAIDD</a></li>
                                    </ul>
                                </li>
                                {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </div>


        {% block content %}
        <!-- Content Goes here -->

        {% endblock content %}
        <!-- Footer -->
        <footer class="page-footer font-small bg-dark pt-4">

            <!-- Footer Elements -->
            <div class="container">

                <!-- Social buttons -->
                <ul class="list-unstyled list-inline text-center">
                    <li class="list-inline-item">
                        <a class="btn-floating btn-fb mx-1">
                            <i class="fab fa-facebook-f"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-tw mx-1">
                            <i class="fab fa-twitter"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-gplus mx-1">
                            <i class="fab fa-google-plus-g"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-li mx-1">
                            <i class="fab fa-linkedin-in"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-dribbble mx-1">
                            <i class="fab fa-dribbble"> </i>
                        </a>
                    </li>
                </ul>
                <!-- Social buttons -->

            </div>
            <!-- Footer Elements -->

            <!-- Copyright -->
            <div class="footer-copyright text-center py-3 footer-font">© 2022 Copyright: Kamil Kwiatkowski
            </div>
            <!-- Copyright -->

        </footer>
        <!-- Footer -->
    </div>
</body>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="https://kit.fontawesome.com/8d6fddefb6.js" crossorigin="anonymous"></script>
</html>

manager/templates/manager/delete_project.html
{%extends 'base.html' %}


{% block content %}
<!-- Delete Project confirmation -->
<div class="row action_field">
    <div class="col center">
        <h2>Delete project form list:</h2>
        <!-- form -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <p>Are you sure you want to delete "{{ object }}"?</p>


            <button class="btn btn-danger" type="submit">Confirm</button>
        </form>
    </div>
</div>
{% endblock content %}

manager/templates/manager/delete_task.html
{% extends 'base.html' %}


{% block content %}
<h2>Delete task form list:</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <p>Are you sure you want to delete "{{ object }}"?</p>

    </div>
    <p>
        <a class="btn btn-primary" href="{% url 'delete_task' %}">Delete task</a>
    </p>
    </div>
</form>
{% endblock content %}

manager/templates/manager/edit_item.html
{% extends 'base.html' %}


{% block content %}
<!-- Edint item -->
<div class="row action_field center">
    <div class="col">
        <h2>Edit task form list:</h2>
        <!-- form -->
        <form method="POST" enctype="multipart/form-data">

            {% csrf_token %}
            <div>
                {{ form.as_p }}
            </div>
            <!-- spacing -->
            <br>
            <hr>
            <br>
            <!-- button -->
            <div class="center">
                <button class="btn btn-primary" type="submit">Edit Item</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

manager/templates/manager/manager_list.html
{% extends 'base.html' %}


{% block content %}
<!-- Content Goes here -->
<!-- if user authenticated  -->
{% if user.is_authenticated %}
{% csrf_token %}
<!-- Task list section -->
<h2 class="center">Task List</h2>
<!-- Task filter -->
<details class="btn btn-primary">
    <summary>Filter data</summary>
    <div class="row">
        <div class="col">

            <div class="table-cell card card-group bg-dark">
                <form class="search" method="get">
                    {{ my_filter.form.as_p }}

                    <button class="btn btn-primary" type="submit">
                        Search
                    </button>
                </form>
            </div>

        </div>
    </div>
</details>
<!-- Task list -->
<div class="table-responsive-md">
    <table class="table table-dark table-striped table-sm align-middle">
        <thead>
            <tr class="table-primary">
                <th>Project</th>
                <th>Task</th>
                <th>Owner</th>
                <th>Due date</th>
                <th>Status</th>
                <th class="center">Edit</th>
                <th class="center">Toggle</th>
                <th class="center">Delete</th>
            </tr>
        </thead>
        {% for item in page_items %}
        <tr>
            <tbody>
                {% if item.done %}
                <td><strike>{{ item.project }}</strike></td>
                <td><strike>{{ item.task }}</strike></td>
                <td><strike>{{ item.owner }}</strike></td>
                <td><strike>{{ item.due_date|date:"D d M Y"}}</strike></td>
                <td><strike>Closed</strike></td>
                {% else %}
                <td>{{ item.project }}</td>
                <td>{{ item.task }}</td>
                <td>{{ item.owner }}</td>
                <td>{{ item.due_date|date:"D d M Y" }}</td>
                <td>Open</td>
                {% endif %}
                <td class="center">
                    <a href="/edit/{{ item.id }}">
                        <button type="button" class="btn btn-primary">Edit</button>

                    </a>
                </td>
                <td class="center">
                    <a href="/toggle/{{ item.id }}">
                        <button type="button" class="btn btn-success">Toggle</button>

                    </a>
                </td>
                <td class="center">
                    <a href="/delete/{{ item.id }}">
                        <button type="button" class="btn btn-danger">Delete</button>
                    </a>
                </td>
        </tr>
        <!-- if list empty -->
        {% empty %}
        <tr>
            <td>No tasks</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<!-- Pagination -->
<div class="row">
    <div class="col">
        <!-- Previous -->
        {% if page_items.has_previous %}
        <a href="?page=1"><button type="button" class="btn btn-primary">&laquo First</button></a>
        <a href="?page={{ page_items.previous_page_number }}"><button type="button"
                class="btn btn-primary">Previous</button></a>
        {% endif %}
        <!-- If has next -->
        {% if page_items.has_next %}

        <div class="col pagination-btnS">
            <a href="?page=={{ page_items.next_page_number }}"><button type="button"
                    class="btn btn-primary">Next</button></a>
            <a href="?page={{ page_items.paginator.num_pages }}"><button type="button" class="btn btn-primary">Last
                    &raquo</button></a>
            {% endif %}
        </div>
    </div>
    <!-- pagination number -->
    <div class="col">
        <p class="page-num">Page {{ page_items.number }} of {{ page_items.paginator.num_pages }}</p>
    </div>
    <!-- Add item button -->
    <div class="col">
        <a type="button" class="btn btn-warning col add-btn" href="/add">Add an Item</a>
    </div>
</div>

<!-- If not authenticated -->
{% else %}
<div class="row">
    <div class="align-content-center flex-wrap center">
        <h3 class="col">Welcome in the Project Management System</h3>
        <br>
        <p class="col">This is the place where your journey begin,
            so please <a class="button" href="{% url 'account_login' %}">Login</a> if you are a user or <a
                class="button" href="{% url 'account_signup' %}">Register</a> yourself
            to receive an access to this page</p>
    </div>
</div>
{% endif %}
{% endblock content %}

manager/templates/manager/projects.html
{% extends 'base.html' %}


{% block content %}
<!-- Project list -->
<form method="POST" enctype="multipart/form-data" action="{% url 'projects' %}">

    <h2 class="center">Project List</h2>
    {% csrf_token %}
    <div class="table-responsive-md">
        <!-- table -->
        <table class="table table-dark table-striped table-sm align-middle">
            <!-- tabke header -->
            <thead>
                <tr class="table-primary">
                    <th class="center">Project</th>
                    <th class="center">Update Project Details</th>
                    <th class="center">Delete Project</th>
                </tr>
            </thead>
            {% for project in project_list %}
            <tr>
                <!-- table data -->
                <tbody>
                    <td>{{ project }}</td>
                    <td class="center">
                        <a href="/update_project/{{ project.id }}">
                            <button type="button" class="btn btn-primary">Update</button>
                        </a>
                    </td>
                    <td class="center">
                        <a href="/delete_project/{{ project.id }}">
                            <button type="button" class="btn btn-danger">Delete</button>
                        </a>
                    </td>
            </tr>
            <!-- <if list empty -->
            {% empty %}
            <tr>
                <td>Here is no project in the list.</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

</form>
<!-- add project button -->
</div>
<p>
    <a class="btn btn-primary" href="{% url 'add_project' %}">Add Project</a>
</p>
</div>
{% endblock content %}

manager/templates/manager/update_project.html
{% extends 'base.html' %}


{% block content %}
<!-- Update project form -->
<div class="row action_field center">
    <div class="col">
        <h2>Update Project:</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <!-- update button -->
            <div class="center">
                <button class="btn btn-primary" type="submit">Update Project</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/manager/add_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List task</title>
</head>
<body>
            <div class="navigation">
                <nav class="navbar navbar-light bg-light navbar-default navbar-static-top">
                    <div class="container-fluid">
                    <a class="navbar-brand" href="#">Offcanvas navbar</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                        <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
                        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li>
                                <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                            </li>
                        </ul>
                        <form class="d-flex">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                        </div>
                    </div>
                    </div>
                </nav>
            </div>

        
        <!-- Projects -->
        <div class="col-lg-3">
            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group me-2" role="group" aria-label="First group">
                <button type="button" class="btn btn-primary rounded-pill">Project one name</button>
                <button type="button" class="btn btn-primary rounded-pill">Project two name</button>
                <button type="button" class="btn btn-primary rounded-pill">Project three name</button>
                <button type="button" class="btn btn-primary rounded-pill">Project four name</button>
                </div>
            </div>
        </div>
     

       
        <h2>Add task to the list:</h2>
        <form mathod="POST" action="add">
            {% csrf_token %}
            <div>
                <p>
                    <label for="id_task">Task:</label>
                    <input type="text" id="id_task" name="item_task" />
                </p>
            </div>
            <div>
                <p>
                    <label for="id_owner">Owner:</label>
                    <input type="text" id="id_owner" name="item_owner" />
                </p>
            </div>
            <div>
                <p>
                    <label for="id_done">Done:</label>
                    <input type="checkbox" id="id_done" name="done" />
                </p>
            </div>
            <div>
                <p>
                    <button type="submit">Add Item</button>
                </p>
            </div>
        </form>



</body>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</html>

templates/manager/manager_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List task</title>
</head>
<body>
            <div class="navigation">
                <nav class="navbar navbar-light bg-light navbar-default navbar-static-top">
                    <div class="container-fluid">
                    <a class="navbar-brand" href="#">Offcanvas navbar</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                        <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
                        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li>
                                <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                            </li>
                        </ul>
                        <form class="d-flex">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                        </div>
                    </div>
                    </div>
                </nav>
            </div>

        
        <!-- Projects -->
        <div class="col-lg-3">
            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group me-2" role="group" aria-label="First group">
                <button type="button" class="btn btn-primary rounded-pill">Project one name</button>
                <button type="button" class="btn btn-primary rounded-pill">Project two name</button>
                <button type="button" class="btn btn-primary rounded-pill">Project three name</button>
                <button type="button" class="btn btn-primary rounded-pill">Project four name</button>
                </div>
            </div>
        </div>
     

       
        <h2>Task List</h2>
        <table>
        
        <table>
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Owner</th>
                    <th>Status</th>
                </tr>
            </thead>
            {% for item in items %}
            <tbody>
                <tr>
                {% if item.done %}
                <td><strike>{{ item.task }}</strike></td>
                <td><strike>{{ item.owner }}</strike></td>
                <td><strike>Close</strike></td>
                {% else %}
                <td>{{ item.task }}</td>
                <td>{{ item.owner }}</td>
                <td>Open</td>
                {% endif %}
                </tr>
                {% empty %}
                <tr><td>All task completed.</td></tr>
            </tbody>
        {% endfor %}
        </table>


</body>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</html>